FROM openjdk:15-ea-15-jdk-buster

RUN curl -L http://apache.crihan.fr/dist/spark/spark-3.0.0-preview2/spark-3.0.0-preview2-bin-hadoop3.2.tgz | \
    tar -xzf - && \
    mv spark-3.0.0-preview2-bin-hadoop3.2 spark